### ISSUE TITLE
Return a specific instance of an XML element - Language

### ISSUE THREAD

**Issue by pmasotagne** [primousers/primo-ve-norm#1]
### To copy a specific element based on its language attribute.

Example:
A record has multiple dc:source elements with different languages.

```
<dc:source xml:lang="ca-ES">Text en català</dc:source>
<dc:source xml:lang="es-ES">Texto en castellano</dc:source>
<dc:source xml:lang="en-US">Text in english</dc:source>
```

Using this rule:
```
rule "Copy source"
when
exist "//*[local-name()='source'][@xml:lang='ca-ES']"
then
copy "//*[local-name()='source'][@xml:lang='ca-ES']/text()" to "dc"."relation"
end
```

Will return:

`<dc:relation>Text en català</dc:relation>`

**Comment by MblackUC** [comment]
Thank you for adding this! We will add this use case and rule to the repository.

Matt

**Comment by MblackUC** [comment]
Hi Pau, I created a branch based off of this issue and https://github.com/primousers/primo-ve-norm/tree/1-return-a-specific-instance-of-an-xml-element-language   

If this looks good to you, we will merge the branch into the main branch of the repo. 

Thank you,
Matt

**Comment by pmasotagne** [comment]
Good morning Matt,

Perfect, go ahead!

Regards,
Pau.
