### ISSUE TITLE
PrimoBO: "Take from first occurrence"

### ISSUE THREAD

**Issue by LincolnUniLTL** [primousers/primo-ve-norm#10]
When there are multiple dc.type fields, import and display only the first one: For instance:

OAI Metadata:
 * \<dc:type\>Dataset</dc:type> 
 * \<dc:type\>Preprint\</dc:type\>

Should return just <dc:type\>Dataset</dc:type>

**Comment by MblackUC** [comment]
In her 2024 ELUNA presentation, Lori Stethers provided and example of a rule that can achieve this. 
https://github.com/lstethers/primove-normrules/blob/main/presentation-files/2024-ELUNA-Creating%20Primo%20VE%20Normalization%20Rules%20for%20External%20Data%20Sources-%20sm.pdf 

From here presentation (slide 25):
when
exist "//*[local-name()='title'][1]/text()"
then
copy "//*[local-name()='title'][1]/text()" to "dc"."title"
end

She also includes a rule to copy "the rest will go into dcterms.alternative" (slide 26)

When
exist "//*[local-name()='title'][position()>1]/text()"
then
copy "//*[local-name()='title'][position()>1]/text()" to "dcterms"."alternative"
end

**Comment by LincolnUniLTL** [comment]
Hi Matt,
Tested this out. This was the coding that worked for me (needed the * before the "local-name"). 

rule "Select first dc:type variable"
when
exist "//*[local-name()='type]/text()"
then
copy "//*[local-name()='type'][1]/text()" to  "dc"."type"
end

rule "Move rest to dcterms:alternative"
when 
exist "//*[local-name()='type'][position()>1]/text()"
then
copy "//*[local-name()='type'][position()>1]/text()" to "dcterms"."alternative"
end

Having said that, I a big fan of actually naming the field (as in "[name()='dc:type']" as local-name directive will also select dcterms:type.

Cheers,
Craig.
