### ISSUE TITLE
PrimoBO: Replace string by string

### ISSUE THREAD

**Issue by LincolnUniLTL** [primousers/primo-ve-norm#14]
Primo back office has the "Replace string by string" transformation built in out of the box. Can this be replicated in XML?

Replaces \<value\> with "\<new value\>" in the first matching string or every instance of the matching string?

**Comment by MblackUC** [comment]
In a 2024 ELUNA presentation, Alice Tippit's presentation included a rule example for "replace string by string":
rule "source"​

when​

true​

then​

 set TEMP"1" to xPath "//*[local-name()='record']/*[local-name()='header']/*[name()='identifier']" ​

 replace string by string (TEMP"1","^objects-","https://blockmuseum.emuseum.com/objects/")​

 set TEMP"1" in "dc"."source"​

End

This rule, stores the identifier value int TEMP 1 and then uses "replace string by string" to find a regex string pattern (^objects-) and do a find and replace on the string matching the regex. '^objects-' is replaced by "https://blockmuseum.emuseum.com/objects/"

For example, if the identifier is 'objects-12345' it will be replaced with "https://blockmuseum.emuseum.com/objects/12345"

**Comment by LincolnUniLTL** [comment]
Kia ora,
I have modified and tested this and moved Alice's suggestion to the code file.
Ngā mihi,
Craig.
