### ISSUE TITLE
PrimoBO: "Take from last occurrence"

### ISSUE THREAD

**Issue by LincolnUniLTL** [primousers/primo-ve-norm#17]
Primo back office has the "Take from last occurrence" transformation built in out of the box. Can this be replicated in XML?

For example, when there are multiple dc.type fields, import and display only the last one: For instance:

OAI Metadata:

<dc:type>Dataset</dc:type>
<dc:type>Preprint</dc:type>

Should return just dc:type\Preprint</dc:type>

**Comment by mwan-work** [comment]
Using **[last()]** should work. So for the above, you can use this:

```
rule "copy last type"
when
	true
then
	copy "//*[name()='dc:type'][last()]" to "dc"."type"
end
```

**Comment by LincolnUniLTL** [comment]
Hi Mike,
I'm just getting back to this after working on another project. This worked for me.
Thank you.
Craig.

**Comment by LincolnUniLTL** [comment]
Moved to Wiki.
