### ISSUE TITLE
Xpath and dc tags

### ISSUE THREAD

**Issue by mwan-work** [primousers/primo-ve-norm#2]
Xpath is notorious for not liking colon characters (":"), which is something used in records that use dc (e.g. \<dc:identifier>, \<dc:title>, etc). In most examples, it is often recommended to use **local-name()** e.g. "**//*[local-name()='identifier']**" , which will capture any element that has the word 'identifier' in it. This might not always be the desired result.

For example, if you had this record:
```
<record xmlns="http://www.openarchives.org/OAI/2.0/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/
    http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
    <header>
        <identifier>IDENTIFIER 1</identifier>

    </header>
    <metadata>
        <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/"
            xmlns:dc="http://purl.org/dc/elements/1.1/"
            xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/
            http://www.openarchives.org/OAI/2.0/oai_dc.xsd">

            <dc:identifier>IDENTIFIER2</dc:identifier>
    
        </oai_dc:dc>
    </metadata>
</record>

```
Using "**//*[local-name()='identifier']**"   will capture both \<identifier> and \<dc:identifier>.

If you want to be specific and target only \<dc:identifier>, then you can use the following xpath:

**[starts-with(name(), 'dc')][contains(name(), 'identifier')]**

This finds any element starting with the letters 'dc', and also containing the word 'identifier'. So the normalisation rule to copy would look something like this:

```
rule "copy dc identifier"
when
	true
then
	copy "//*[starts-with(name(), 'dc')][contains(name(), 'identifier')]/text()" to "dc"."identifier"
end

```
Conversely, if you only want the value in \<identifier> and NOT \<dc:identifier> then you can use:

**[not(starts-with(name(), 'dc')) and contains(name(), 'identifier')]**

```
rule "copy identifier"
when
	true
then
	copy "//*[not(starts-with(name(), 'dc')) and contains(name(), 'identifier')]/text()" to "dc"."identifier"
end

```

**Comment by MblackUC** [comment]
Thank you for sharing this Mike! Let's collaborate to add this to the repository.
Matt

**Comment by LincolnUniLTL** [comment]
Hi Mike, 
Thank you for sharing you thoughts and code. 
I have verified that your code works for us, and would like to include your explanation and code in our repository. We'd also like to attribute you as the author so please let us know 1) if that would be acceptable and 2) if we can cite your username ([mwan-work](https://github.com/mwan-work)).
Regards,
Craig.

**Comment by mwan-work** [comment]
Hi Craig, yes to 1) and 2) - feel free to add to the repository 👍 

Regards, Mike
