### ISSUE TITLE
Normalizing HTML entity codes for XML?

### ISSUE THREAD

**Issue by nbabb1** [primousers/primo-ve-norm#21]
I'm using XML rules for normalization in discovery import profiles to allow actions not possible with DC -- but some of the fields that import fine with DC rules aren't importing properly with XML. When the source fields include HTML links, using &lt; and &gt; for the < and > characters, with DC the fields import and display/function fine in Primo VE. But with XML, the entity values break the fields and don't display nor work in Primo VE.
I see in Ex Libris documentation that there is:
replace string by string – This action replaces all occurrences of a regular expression with a specified value. Valid format:
replace string by string (TEMP"{i}","<Java_regex>","<string>")
So I thought maybe I could use this -- but I can't figure out to write a rule that works within the XML discovery normalization rule. Can anyone help with this, or do you have a suggestion for a better way to fix this problem?

**Comment by LincolnUniLTL** [comment]
Hi nbabb1,
I think you are on the right path, but are you able to provide an example of a URL that contains the characters you would like normalised?
Regards,
Craig.

**Comment by nbabb1** [comment]
Hi, Craig,
Thanks so much! Here's are a couple of examples:
```
<dc:relation>&lt;a href="http://www.hallwalls.org/perflit/709.html"&gt;http://www.hallwalls.org/perflit/709.html&lt;/a&gt;</dc:relation>
<dc:rights>Contact the Poetry Collection: &lt;a href="http://library.buffalo.edu/pl/"&gt;http://library.buffalo.edu/pl/&lt;/a&gt;</dc:rights>
```
My XML rules are very simple; just:
```
rule "Copy relation"
when
exist "//*[local-name()='relation']"
then
copy "//*[local-name()='relation']/text()" to "dc"."relation"
end
```
Best,
--Nancy

**Comment by LincolnUniLTL** [comment]
Hi Nancy,

Try using:

rule "Copy relation"
when
exist "//*[local-name()='relation']"
then
copy "//*[name()='dc:relation']" to  "dc"."relation"
end

```
<dc:relation>&lt;a href="http://www.hallwalls.org/perflit/709.html"&gt;http://www.hallwalls.org/perflit/709.html&lt;/a&gt;</dc:relation> 

 Normalises to:

 "dc":"relation"<a href="http://www.hallwalls.org/perflit/709.html">http://www.hallwalls.org/perflit/709.html</a>"
```
The "/text()" element selects the individual text elements in the field so you end up with multiple "dc":"relation" elements containing one letter/word. Just a straight copy/mapping command worked for me.

Let me know how you get on.

Cheers,
Craig.

**Comment by nbabb1** [comment]
Aha! And of course -- that makes sense! Thank you!

**Comment by LincolnUniLTL** [comment]
You are welcome. I'm going to close this issue now. 
Regards,
Craig.
