### ISSUE TITLE
Set "discovery"."resourceType" with one exception

### ISSUE THREAD

**Issue by alsalatkajr** [primousers/primo-ve-norm#24]
I used this rule to ensure all records imported from Digital Commons had the same resource type suggested by our Special Collections team, except for our items in the "Masters Theses and Doctoral Dissertations" set.

rule "all archival materials" 
when
"dc"."source" not equals "Masters Theses and Doctoral Dissertations"
then 
set "Archival Material" in "discovery"."resourceType" 
end

**Comment by LincolnUniLTL** [comment]
Kia ora alsalatkajr,

I'm sorry about the delay but the teams workload commitments meant that this volunteer project had a lower priority over the last month.

Just a note, I tried your code but there was a compilation error when created as an XML normalisation. The XML code that did work was:

rule "all archival materials"
when
"//*[local-name()='source']/text()" not equals "Masters Theses and Doctoral Dissertations"
then
set "Archival Material" in "discovery"."resourceType"
end

Ngā mihi,
Craig.

**Comment by LincolnUniLTL** [comment]
Combined with https://github.com/primousers/primo-ve-norm/issues/25, added to code base and closed.
