### ISSUE TITLE
Setting "discovery"."resourceType" using data from "dc"."source"

### ISSUE THREAD

**Issue by alsalatkajr** [primousers/primo-ve-norm#25]
This rule ensures that records imported from Digital Commons in the "Masters Theses and Doctoral Dissertations" set have the same and  accurate resource type applied.

rule "theses and dissertations in scholar"
when
"dc"."source" equals "Masters Theses and Doctoral Dissertations"
then
set "dissertations" in "discovery"."resourceType"
end

**Comment by LincolnUniLTL** [comment]
Kia ora alsalatkajr,

Just a note, I tried your DC code but there was a compilation error when created as an XML normalisation. The XML code that did work was:

rule "theses and dissertations in scholar"
when
"//*[local-name()='source']/text()" equals "Masters Theses and Doctoral Dissertations"
then
set "dissertations" in "discovery"."resourceType"
end

As this is similar in context to issue [24](https://github.com/primousers/primo-ve-norm/issues/24), I might merge these two issues.

Ngā mihi,
Craig.

**Comment by LincolnUniLTL** [comment]
Combined with https://github.com/primousers/primo-ve-norm/issues/24, added to code base and closed.
