### ISSUE TITLE
Moving values between fields

### ISSUE THREAD

**Issue by alsalatkajr** [primousers/primo-ve-norm#26]
This pair of rules removes thumbnail URL's that live in "dc"."description" upon import from Digital Commons and moves them to a DC field that is not configured for display. For our dissertations, "dc"."description" is only used for the abstract and was considered important for display. The second rule moves the abstract in each record back to "dc"."description" based on the "discovery"."resourceType"

rule "move description to relation"
when
exist "dc"."description"
then
move "dc"."description" to "dc"."relation"
end

rule "move relation back to description"
when
"discovery"."resourceType" equals "dissertations"
then
move "dc"."relation" to "dc"."description"
end

**Comment by LincolnUniLTL** [comment]
Hi [alsalatkajr](https://github.com/alsalatkajr),
Thank you for your contribution. I have now moved this to the code base as [Moving values between fields](https://github.com/primousers/primo-ve-norm/blob/main/Moving%20values%20between%20fields).
Regards,
Craig.
