### ISSUE TITLE
Removing timestamp information from "dc"."date" to allow year to import

### ISSUE THREAD

**Issue by alsalatkajr** [primousers/primo-ve-norm#27]
Our values for "dc"."date" in Digital Commons records are timestamped (end in Z) and do not import as noted in ExLibris documentation. This rule allows us to remove all characters after the first "-" in the date field, leaving only the year as the value in "dc"."date", meaning it can import.

rule "remove timestamp for utc scholar date"
when 
exist "dc"."date"
then
set TEMP"1" to dc value "dc"."date"
remove substring using regex (TEMP"1","-.*")
set "dc"."date" to TEMP"1"
end

**Comment by LincolnUniLTL** [comment]
Hi [alsalatkajr](https://github.com/alsalatkajr),
Just looking at this now and wondering if you have seen our other [date example](https://github.com/primousers/primo-ve-norm/blob/main/Select%20the%20appropriate%20Date%20value%20for%20a%20record) which contains 4 different variants of this code in xml?
I'm going to close this issue with our gratitude. 
Regards,
Craig.
