### ISSUE TITLE
Remove exact phrase from "dc"."language"

### ISSUE THREAD

**Issue by alsalatkajr** [primousers/primo-ve-norm#28]
rule "remove phrase from language"
when
TRUE
then
remove "dc"."language" if equals "This collection contains materials in English."
end

**Comment by LincolnUniLTL** [comment]
Hi [alsalatkajr](https://github.com/alsalatkajr),
Thank you for your contribution. I have combined this with [issue 30](https://github.com/primousers/primo-ve-norm/issues/30), converted the combine rule into xml, tested it and now moved this to the code base as [Exclude import of dc field based on exact phrase](https://github.com/primousers/primo-ve-norm/blob/main/Exclude%20import%20of%20dc%20field%20based%20on%20exact%20phrase).
Regards,
Craig.
