### ISSUE TITLE
Move "dc"."coverage" to "dc"."subject"

### ISSUE THREAD

**Issue by alsalatkajr** [primousers/primo-ve-norm#29]
This rule moves values in "dc"."coverage" in ArchivesSpace to "dc"."subject" to allow for display. Local practice in ArchivesSpace for us places subjects that are geographical names in "dc"."coverage"

rule "move coverage to subject"
when
exist "dc"."coverage"
then
move "dc"."coverage" to "dc"."subject"
end

**Comment by LincolnUniLTL** [comment]
Kia ora alsalatkajr,

Thank you for adding your DC code to our project.

Just a note, I tried your code but there was a compilation error when created as an XML normalisation. The XML code that did work was:

rule "move coverage to subject"
when
exist "//*[local-name()='coverage']/text()"
then
copy "//*[local-name()='coverage']/text()" to "dc"."subject"
end

Ngā mihi,
Craig.

**Comment by LincolnUniLTL** [comment]
Moved to wiki and closed.
