### ISSUE TITLE
Remove exact phrase from "dc"."publisher"

### ISSUE THREAD

**Issue by alsalatkajr** [primousers/primo-ve-norm#30]
Collection Areas in ArchivesSpace import under "dc"."publisher" and did not need to be configured for display.

rule "remove CHC from publisher"
when
TRUE
then
remove "dc"."publisher" if equals "Chattanooga History Collections"
end

**Comment by LincolnUniLTL** [comment]
Hi [alsalatkajr](https://github.com/alsalatkajr),
Thank you for your contribution. I have combined this with [issue 28](https://github.com/primousers/primo-ve-norm/issues/28), converted the combine rule into xml, tested it and now moved this to the code base as [Exclude import of dc field based on exact phrase](https://github.com/primousers/primo-ve-norm/blob/main/Exclude%20import%20of%20dc%20field%20based%20on%20exact%20phrase).
Regards,
Craig.

**Comment by LincolnUniLTL** [comment]
Closing issue with thanks.
