### ISSUE TITLE
Question about behavior of the rule for selecting a certain instance of an element.

### ISSUE THREAD

**Issue by frenchfrybrary** [primousers/primo-ve-norm#4]
Hello!

I have a question about the "This rule can be used to select a certain instance of an element to return" rule.

I was able to successfully apply this normalization rule. However, when I run it with a test record, it strips out all elements entirely except the one instance of the element:

![image](https://github.com/primousers/primo-ve-norm/assets/49535035/fd8ac267-0c5d-4692-b8dc-945dcc600352)

Am I doing something wrong?? This is the rule:

rule "extra scholarworks identifiers"
when
exist "//*[local-name()='identifier']"
then
copy "//*[local-name()='identifier'][not(contains(text(),'viewcontent'))][1]" to "dc"."identifier"
end

Thank you!

**Comment by LincolnUniLTL** [comment]
Hi [**frenchfrybrary**](https://github.com/frenchfrybrary)**,**

**Unlike full DC normalisation rules where there is a default set of identifiers loaded automatically, when using XML norm rules you have to manually select which identifiers you need. For instance, the first rule of each XML normalisation profile indicates the fields that we want to load by default:**

**rule "Default DC fields"**  
**when**  
 **not exist "//\*\[local-name()='setSpec'\]\[contains(text(),'col\_XXX\_XXXX')\]"**  
**then**  
 **copy "//\*\[name()='dc:title'\]" to "dc"."title"**  
 **copy "//\*\[name()='dc:creator'\]" to  "dc"."creator"**  
 **copy "//\*\[name()='dc:contributor'\]" to  "dc"."contributor"**  
 **copy "//\*\[name()='dc:subject'\]" to  "dc"."subject"**  
 **copy "//\*\[name()='dc:description'\]" to  "dc"."description"**  
 **copy "//\*\[name()='dc:publisher'\]" to  "dc"."publisher"**  
 **copy "//\*\[name()='dc:format'\]" to  "dc"."format"**  
 **copy "//\*\[name()='dc:identifier'\]" to  "dc"."identifier"**  
 **copy "//\*\[name()='dc:language'\]" to  "dc"."language"**  
 **copy "//\*\[name()='dc:relation'\]" to  "dc"."relation"**  
 **copy "//\*\[name()='dc:type'\]" to  "dc"."type"**  
**end**

**I can't instantly find the documentation that outline this, but I hope this helps.**

**Craig.**
