### ISSUE TITLE
Normalise Austlang codes

### ISSUE THREAD

**Issue by yanan918** [primousers/primo-ve-norm#5]
Issue contributed by Stacey van Groll [s.vangroll@library.uq.edu.au]

When there are Austlang languages, parse the data to only the code to map against the Customised Languages mapping table.

Austlang languages are referred to with first the language which may be one, two, or three words with characters between them, then a space, then the word language, then a space, and then the code for the language. 

There are 1,200+ Austlang codes. The code always has an upper case character first, then may have one, two or three digits, then may have a full stop, and then the full stop may be followed by a digit or an upper case character. The Austlang data needs to be in an exact form in order to be mapped against the Customised Languages mapping table, with entries such as lang.a89 The record must also include dc:language field of aus but may also have other data such as an additional entry of eng. 

The outcome is correct representation in UI by Language facet and Language Details record display, with facet values of both Australian languages and the Austlang language, allowing for nested or granular language selection. In Primo Back Office, this is handled by a normalisation rule parsing the data to obtain the code and transform to necessary form by the most structured aspect, being the code at the end of the string, which is always preceded by the word language, then a space, and then the code.

For example, 
![image](https://github.com/primousers/primo-ve-norm/assets/72056315/0387e789-bf79-4007-9a32-7dee3b98fcff)

**Comment by LincolnUniLTL** [comment]
By coincidence, ExLibris updated the “Customized Languages Codes” table, adding the [1500+ Austlang codes](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/050Display_Configuration/Configuring_Austlang_and_Custom_Languages_for_Primo_VE) in the May 5th release. It may have affected the code naming taxonomy in the main “Language codes Labels” table so I will look at getting the code updated to align with the new code names.

**Comment by LincolnUniLTL** [comment]
Final code committed and issue closed

**Comment by SvanGroll** [comment]
1.	I find that the data is not normalised from the code to the language in the full record display when a lower case prepend of lang is included, despite that the Customized Language code table entries include lang as a prepend. For example dc:language of lang.e81 displays in the full record Language field as e81 when it should display as Jarowair. I have confirmed that the full record display Language field is as expected when adjusting to remove this portion: add prefix (TEMP"1","lang.")
2.	I’m not sure if it’s some sort of indexing issue, or something else I’m missing in the configuration, but currently the data is only being added to display and not the search (and therefore not also the facet)
3.	The rule only works on one instance of an Austlang code language per record, when it should take effect on all instances. For example, a record with Jarowair language E81 and Wakka Wakka language E28 only displays Jarowair and does not display Wakka Wakka. I am having a great deal of trouble trying to figure out a solution for this given the apparent limitations of Xpath version 1.0 which does not allow looping or conditions within the rule, and still avoids duplicated data
4.	Additional note: The comment on April 23 2024 is that Ex Libris updated the Austlang codes on May 5th Release for Primo VE. I’m not sure where this information came from, as the codes have been in place from October 2021 for Primo VE, I can find no record of this nor see any changes. But I don't think this is related to the other issues I've mentioned

**Comment by LincolnUniLTL** [comment]
Kia ora Stacey,
Thank you for your comments.

1. It is interesting that only the language code is required and not the "lang." prefix. I'll modify the code. Thank you.
2. Adding search and facet data is a two step process. You would first import and normalise the data and ensure the is in the desired dc field. Step two is accomplished by [adding local fields](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/050Display_Configuration/040Configuring_Local_Display_and_Search_Fields_for_Primo_VE). Once you have created the local field, you can enable it for search and/or faceting. You then configure the "DC Normalise Rules" panel to add a drool for the appropriate value in the display, index and facet sections.
3. Yes this is the real limitation and is a [known issue](https://github.com/primousers/primo-ve-norm/wiki/3.-Known-Issue-with-Discovery-Import-Norm-Rules). If you have multiple values, then you will need multiple instances of the rule.
4. Agreed, this shouldn't affect the normalisation.

Let me know if you have any other questions.
Ngā mihi,
Craig.

**Comment by SvanGroll** [comment]
Hi Craig,

2. This is not mapping to a local field, but is utilising the OTB Language field. Apologies if I'm missing something here, but I have adjusted other XML external data sources by normalisation rules for similar local fields like Author and Subject, and the data appears in the search>facet for Primo VE without any extra effort. I'm suspecting this is a defect.

3. I am finding this difficult to create a rule with multiple iterations for a potentially very high number of languages in Austlang that may be in our records which also does not result in unexpected data, including by apparent inability in XPath 1.0 to check for the field already existing and handle appropriately. For example:
Primo BO data: <language>aus;eng;C15;C6;C8;C7.1;C8.1</language>
Primo VE data: "language" : [ "aus;eng;c15;c6;c8;luritja language c7.1;c8.1;pitjantjatjara language;eastern arrernte language;western arrernte language;anmatyerre language;ukatja language" ],

New items:
5. I have found another defect with VE that it fails to display "Undetermined" if the text in the Language field is not present in the relevant Language mapping table. 
Instead it displays the text normalised by the rule, which worsens the problems noted above in 3 and can be seen in the example above.

6. I find that the rule currently is not strict enough, in being based on the presence of the word 'language' in the subject, as there are other non-Austlang subjects with the word 'language'.
For example:
**Raw subject data**: English language -- Dialects -- Queensland
**“Language” display field**: dialects queensland
The regular expression I created in BO accounts for the specs of complexities I determined for Austlang, with Austlang languages having first the language which may be one, two, or three words with characters between them, then a space, then the word language, then a space, and then the code for the language. The code always has an upper case character first, then may have one, two or three digits, then may have a full stop, and then the full stop may be followed by a digit or an upper case character.
Given these complexities, I determined it was better to work backwards from the end of the string to separate out just the necessary code to reference against the mapping table, and implemented a BO transformation to take all matching strings by: language\s([A-Z]\d{1,3}(\.[A-Z0-9]+)?)$ 

----------

I have opened a case regarding these problems, which is high priority also as I have received multiple assurances from Ex Libris Primo Product Management and via the Go VE channel that this functionality is supported in Primo VE, as a feature alignment issue from Primo BO. This includes from the documentation published in 2021, and correspondence in December 2023 and April 2024.

Cheers,
SvG

**Comment by LincolnUniLTL** [comment]
Hi Stacey,

I've been out of the office for most of the last two days (office party season) so I'll have a look at your comments and get back to you tomorrow.

Cheers,
Craig.

**Comment by SvanGroll** [comment]
Part of this issue will be resolved in the coming May 2025 per my case, with this Resolved Issue now documented:

"May 2025 SF: 07862532
The set action could not process a variable list of items returned from the return list using regex transformation for external normalization rules. This has been fixed by adding the set list action to support lists (not strings). For more information, see [Normalization Rule Syntax for DC and XML Formats](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/100Loading_Records_from_External_Sources_into_Primo_VE/Configuring_Normalization_Rules_for_External_Resources_(Primo_VE)#Normalization_Rule_Syntax_for_DC_and_XML_Formats)."

Summary of my cases, with two others pending correction in upcoming releases:

• 07807052 - VE PRIORITY - Unexpected Austlang language appearance in Primo VE from external source data by XML normalisation via Discovery Import Profile >>> Tentative fix advised for June 2025 Release 
• 07862532 - Cloned case: VE PRIORITY - External XML NR transformation Return List using Regex is not working >>> Resolved issue in May 2025 Release
• 07862530 - Cloned case: VE PRIORITY - Unrecognized language entries should appear as 'Undetermined' >>> Tentative fix advised for August 2025 Release
